### ISSUE TITLE
cannot connect to script

### ISSUE THREAD

**Issue by ghost** [jbags81/fabric-home-assistant#4] opened 2016-05-23 22:04 UTC
When I follow your instructions I get to the point of entering

wget -Nnv https://raw.githubusercontent.com/home-assistant/fabric-home-assistant/master/hass_rpi_installer.sh && bash hass_rpi_installer.sh;

I get at the prompt

GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [0] : close notify
Unable to establish SSL connection.

Any ideas?

This is with a fresh install of Raspian 2016-05-10

**Comment by Landrash** [comment] 2016-06-01 07:04
My guess is that the dns lookup of failed for some reason.
Have you solved this or is it stil a problem?
If it's still a problem try to verify that you can ping `github.com`  for example. If that's not the case have a look at your `/etc/resolvconf.conf`. There should be atleast one dns server in this file and if not you could edit it to contain

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

In this case I used google's dns servers but any publicly available server will work.

**Comment by patchedsoul** [comment] 2016-06-02 04:54
@mik9dt as @Landrash has advised, can you confirm the issue is resolved?

**Comment by patchedsoul** [comment] 2016-06-05 02:23
closing as non-issue

**Closed as completed by patchedsoul** 2016-06-05 02:23 UTC
